### PR TITLE
Upgrade json api

### PR DESCRIPTION
**Pull request by manojlds**
Upgrades publish, material, fetch.
Lots of potential for refactor, but can be taken up later.

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
@manojlds I see a lot of changes for this API migration. Please go ahead with the merge, if you've checked this build on one of the go server.

**Comment by ashwanthkumar** [comment]
LGTM

**Comment by ashwanthkumar** [comment]
@manojlds I guess with Github's Review system in place, we can remove the pullapprove dependency from the repo?

**Comment by manojlds** [comment]
Fixes #50 #6

**Pull request merged**
